### ISSUE TITLE
static-marks returns no error when it failed to parse the yml-file

### ISSUE THREAD

**Issue by gaerfield** [darekkay/static-marks#10]
Given the following bookmarks-yaml-file:
```yaml
test:
  - duckduckgo: https://duckduckgo.com/
    - more duck: https://duckduckgo.com/
```
static-marks will output an error (which is absolutely fine), but the return value is still '0':
![image](https://user-images.githubusercontent.com/65171481/84890124-45c1c380-b09a-11ea-8916-8d0b1cfe1903.png)

Further information: Within an automatic build, this will result in a html-file containing no links whereas the build just runs fine. This finally results in overwriting a fine version of a page with an empty one.
