### ISSUE TITLE
Treat notes starting with "http" as links

### ISSUE THREAD

**Issue by darekkay** [darekkay/static-marks#12]
There are currently two types of notes: **text notes** and **link notes** (nested links). 

Example bookmarks file:

```yaml
Collection:
  - Bucket:
    - Link:
      - https://example.com
      - Text note
      - Link note: https://example.com
      - https://example.com
```

The current result:

![image](https://user-images.githubusercontent.com/3101914/94340024-bf087500-fffe-11ea-8d4d-95b182912937.png)

It would be nice to turn text notes automatically into clickable links if they start with `http` (or maybe even other supported protocols).
