### ISSUE TITLE
[Request] Add icons to bookmarks links

### ISSUE THREAD

**Issue by smed79** [darekkay/static-marks#37]
Hi, 

instead of the <ins>standard</ins> svg icon beside the link ![bookmark-svg](https://user-images.githubusercontent.com/1873139/192486767-a1acf0da-1286-4113-9d8d-01d110338ec6.png)

I would like to have (as other users) the ability to change it to a local or remote icon file.

That would help a lot as an icon is **more speaking** than a text.

<ins>Before:</ins>

![static-marks-before](https://user-images.githubusercontent.com/1873139/192468552-3c5bd91c-6372-4cd9-b205-d49826eb3dd2.png)

<ins>After:</ins>

![static-marks-after](https://user-images.githubusercontent.com/1873139/192468625-eb76c076-49ae-4592-a3f0-a39b18a9c16b.png)

**Suggestion of formating**
```yaml
Collection:
  - Bucket:
      - Link: https://example.com
      - ![fav](icons/example.com.png)
```
or
```yaml
Collection:
  - Bucket:
      - Link: https://example.com
      - ![fav](https://example.com/favicon.png)
```
or
```yaml
Collection:
  - Bucket:
      - Link: https://example.com
      - ![fav](data:image/png;base64,...)
```

Anything that works is welcome.
