### ISSUE TITLE
Adding bookmarks using Apple Shortcuts

### ISSUE THREAD

**Issue by roelvangils** [darekkay/static-marks#41]
I'm thinking of ways to make it easier to add new bookmarks to my`bookmarks.yml` file from within the browser itself (just like one normally does). My first idea was to write a Shortcut action (or use Keyboard Maestro) that executes a shell script that appends a line to the file, like so:

```yaml
Unsorted:
  - These bookmarks have been added via the shortcut:
      - Darek's website: https://darekkay.com/static-marks/
```  

After doing...

```bash
echo "      - New bookmark: https://www.example.com/" | tee -a bookmarks.yml
```

**Note**: with Apple Shortcuts or KM it's pretty easy to get the page title and URL of the active page in Chrome or Safari.

You'll get this:

```yaml
Unsorted:
  - These bookmarks have been added via the shortcut:
      - Darek's website: https://darekkay.com/static-marks/
      - New bookmark: https://www.example.com/
```  

And the same shortcut action could then also rebuild the `bookmarks.html` file. And then, periodically, I would just open the YAML file to move and organise the newly added bookmarks.

Or am I totally overthinking it? I haven't built it yet, so I'd like to hear what you think.
